[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./migration up && ./dakopi"
restartPolicyType = "ON_FAILURE"
health_check_path = "/api/health"
health_check_timeout = 300
